import type { RoyaFixture } from './types.ts';

export const royaFixture: RoyaFixture = {
  project: {
    id: '5b00e3dd-a55d-4cae-93df-e0618fa81a58',
    code: 'dawn-over-cairo',
    titleAr: 'فجر القاهرة',
    titleEn: 'Dawn Over Cairo',
    kind: 'film',
    shootingWeeks: 4,
    totalBudgetPiastres: 4_800_000,
    baseCurrency: 'EGP',
    contingencyBasis: 'percentage',
    contingencyRate: 0,
    contingencyPiastres: null,
    producerMarginPiastres: 0,
    vatRate: 0,
    status: 'active',
  },
  budget: {
    versionNumber: 1,
    labelAr: 'النسخة الأولى',
    labelEn: 'Initial version',
    lines: [
      {
        id: 'c171c1d4-cee0-4f60-905e-57efc711689d',
        lineNumber: 1,
        departmentAr: 'فريق التصوير',
        departmentEn: 'Shooting crew',
        nameAr: 'طاقم الكاميرا الأسبوعي',
        nameEn: 'Weekly camera crew',
        costStrategy: 'weekly_x_weeks',
        inputs: { weekly_rate: 500_000, weeks: 4, uses_project_weeks: true },
        plannedTotalPiastres: 2_000_000,
        currency: 'EGP',
        vatApplicable: false,
        status: 'approved',
      },
      {
        id: '498a9040-b083-4c70-b448-c84c9a69ca89',
        lineNumber: 2,
        departmentAr: 'المعدات',
        departmentEn: 'Equipment',
        nameAr: 'حزمة معدات ثابتة',
        nameEn: 'Fixed equipment package',
        costStrategy: 'lump',
        inputs: { amount: 2_000_000 },
        plannedTotalPiastres: 2_000_000,
        currency: 'EGP',
        vatApplicable: false,
        status: 'approved',
      },
    ],
  },
};
