import type { Language } from './domain/types';

const messages = {
  en: {
    sample: 'Local sample data',
    reset: 'Reset',
    backPortfolio: 'Portfolio',
    projects: 'Projects',
    active: 'Active',
    film: 'Film',
    budget: 'Budget',
    settings: 'Settings',
    totalBudget: 'Budget cap',
    plannedApproved: 'Planned (approved)',
    shootingWeeks: 'Shooting weeks',
    version: 'Version 1',
    budgetIntro: 'A small read-only slice of the active budget version.',
    departmentSubtotal: 'Department subtotal',
    approved: 'Approved',
    weeklyStrategy: 'Weekly × weeks',
    lumpStrategy: 'Lump sum',
    weeklyCrew: 'Weekly camera crew',
    fixedEquipment: 'Fixed equipment package',
    shootingCrew: 'Shooting crew',
    equipment: 'Equipment',
    financialSettings: 'Financial settings',
    fixtureSettings: 'The sample uses zero add-ons so the source preview total stays directly traceable to approved lines.',
    contingency: 'Contingency',
    producerMargin: 'Producer margin',
    vatRate: 'VAT rate',
    sourceRule: 'Preview basis',
    approvedLinesOnly: 'Approved budget lines only',
    shootingWeeksDescription: 'Lines that opted in to inherit the project shooting weeks will be recomputed.',
    changeWeeks: 'Change shooting weeks',
    modalSubtitle: 'Preview which lines will be recomputed before saving.',
    close: 'Close',
    current: 'Current',
    newValue: 'New value',
    weeksUnit: 'weeks',
    previewImpact: 'Preview impact',
    before: 'Before',
    after: 'After',
    line: 'Line',
    delta: 'Δ',
    capWarning: 'New total exceeds the project budget cap.',
    previewOnly: 'Preview only · this sample never writes project or budget data.',
    cancel: 'Cancel',
    invalidWeeks: 'Enter a whole number from 1 to 520.',
    unchanged: 'Unchanged',
    inherited: 'Inherits project weeks',
    noVat: 'Not VAT applicable',
  },
  ar: {
    sample: 'بيانات تجريبية محلية',
    reset: 'إعادة الضبط',
    backPortfolio: 'العودة للمعرض',
    projects: 'المشاريع',
    active: 'نشط',
    film: 'فيلم',
    budget: 'الميزانية',
    settings: 'الإعدادات',
    totalBudget: 'حد الميزانية',
    plannedApproved: 'المخطط المعتمد',
    shootingWeeks: 'أسابيع التصوير',
    version: 'النسخة 1',
    budgetIntro: 'جزء صغير للقراءة فقط من نسخة الميزانية النشطة.',
    departmentSubtotal: 'مجموع القسم',
    approved: 'معتمد',
    weeklyStrategy: 'أسبوعي × أسابيع',
    lumpStrategy: 'مبلغ مقطوع',
    weeklyCrew: 'طاقم الكاميرا الأسبوعي',
    fixedEquipment: 'حزمة معدات ثابتة',
    shootingCrew: 'فريق التصوير',
    equipment: 'المعدات',
    financialSettings: 'إعدادات مالية',
    fixtureSettings: 'تستخدم العينة إضافات صفرية ليظل إجمالي المعاينة قابلاً للتتبع مباشرة إلى البنود المعتمدة.',
    contingency: 'الاحتياطي',
    producerMargin: 'هامش المنتج',
    vatRate: 'نسبة الضريبة',
    sourceRule: 'أساس المعاينة',
    approvedLinesOnly: 'بنود الميزانية المعتمدة فقط',
    shootingWeeksDescription: 'البنود التي اختارت اتباع أسابيع التصوير للمشروع سيُعاد حسابها.',
    changeWeeks: 'تعديل أسابيع التصوير',
    modalSubtitle: 'اعرض البنود التي سيُعاد حسابها قبل الحفظ.',
    close: 'إغلاق',
    current: 'الحالي',
    newValue: 'القيمة الجديدة',
    weeksUnit: 'أسابيع',
    previewImpact: 'معاينة التأثير',
    before: 'قبل',
    after: 'بعد',
    line: 'البند',
    delta: 'Δ',
    capWarning: 'الإجمالي الجديد يتجاوز حد ميزانية المشروع.',
    previewOnly: 'معاينة فقط · هذه العينة لا تكتب بيانات المشروع أو الميزانية.',
    cancel: 'إلغاء',
    invalidWeeks: 'أدخل عدداً صحيحاً من 1 إلى 520.',
    unchanged: 'بدون تغيير',
    inherited: 'يتبع أسابيع المشروع',
    noVat: 'لا يخضع للضريبة',
  },
} as const;

export type MessageKey = keyof typeof messages.en;

export function copy(language: Language, key: MessageKey): string {
  return messages[language][key];
}
